"""Create, build, and optionally bundle a generated BOPE target."""

from __future__ import annotations

import json
import os
from pathlib import Path
import re
import shutil

from .common import atomic_text, digest, note, relative_or_absolute, run_logged
from .contract import ContractResult
from .errors import BopeError
from .kernel import KernelArtifacts
from .ota import OtaInfo


GENERIC_ENGINE_TOOLS = {
    "analyze-run-log.py",
    "audit-profile.py",
    "build-manifest.py",
    "check-critical-reclaim.py",
    "collect-forensics.sh",
    "common.sh",
    "compare-elf.py",
    "derive-symbol-offsets.py",
    "extract-btf-layouts.sh",
    "preflight-device.sh",
    "scaffold-target.py",
    "stage-timer.py",
}


def find_donor(project: Path, pre_build: str) -> Path:
    for header in sorted(project.glob("targets/*/brazilian-open-payload-engine/src/target.h")):
        text = header.read_text(errors="replace")
        if re.search(rf'^#define\s+TARGET_BUILD\s+"{re.escape(pre_build)}"\s*$', text, re.MULTILINE):
            return header.parents[2]
    raise BopeError(f"no BOPE donor target matches OTA source build {pre_build}")


def _copy_engine(donor: Path, destination: Path, slug: str, build: str) -> None:
    source = donor / "brazilian-open-payload-engine"
    if not source.is_dir():
        raise BopeError(f"donor BOPE engine is missing: {source}")

    def ignored(path: str, names: list[str]) -> set[str]:
        relative = Path(path).relative_to(source)
        result = {name for name in names if name in {"build", "evidence", "__pycache__"}}
        if relative == Path("."):
            result.update({name for name in names if name.startswith("zzhl-root-snapshot-")})
            result.update({"STATUS.md", "docs"} & set(names))
        if relative == Path("tools"):
            result.update(name for name in names if name not in GENERIC_ENGINE_TOOLS and name != "README.md")
        return result

    shutil.copytree(source, destination, ignore=ignored)
    (destination / "docs").mkdir(exist_ok=True)
    (destination / "docs/README.md").write_text(
        f"# {build} target documentation\n\n"
        "The generated firmware contract lives in `../src/target.h`.\n"
        "Port provenance and inherited calibration values are recorded in "
        "`../../port-manifest.json`.\n"
    )
    makefile = destination / "Makefile"
    text = makefile.read_text()
    text = re.sub(r"^LAUNCHER_BIN\s*:=.*$", f"LAUNCHER_BIN := $(OUTDIR)/stability-launcher-{slug}", text, flags=re.MULTILINE)
    text = re.sub(
        r"-DREL_GATE_NAME='\"[^\"]+\"'",
        f"-DREL_GATE_NAME='\"{slug}-fresh\"'",
        text,
    )
    makefile.write_text(text)

    for old in list((destination / "src").glob("target_*.h")):
        if old.name != "target.h":
            new = old.with_name(f"target_{slug}.h")
            guard = f"BOPE_TARGET_{slug.upper()}_COMPAT_H"
            new.write_text(
                f"#ifndef {guard}\n#define {guard}\n\n"
                "/* Compatibility include for external users. New code includes target.h. */\n"
                '#include "target.h"\n\n#endif\n'
            )
            if new != old:
                old.unlink()

    (destination / "README.md").write_text(
        f"# {build} Brazilian Open Payload Engine\n\n"
        "This target was generated by `tools/bope-from-ota`. Firmware symbols "
        "and BTF-derived layouts were rebuilt from the target boot image. "
        "Allocator and timing calibration inherited from the donor remains "
        "explicitly marked in `../port-manifest.json`.\n\n"
        "Validation:\n\n"
        "```sh\n"
        f"../../../tools/bope-verify-target --header src/target.h "
        f"--elf ../firmware/vmlinux_{slug.upper()}.elf "
        f"--btf ../firmware/vmlinux_{slug.upper()}.btf\n"
        "make test-aar-read-plan test-fops-layout test-compact-log\n"
        "make so\n"
        "```\n"
    )
    (destination / "tools/README.md").write_text(
        "# BOPE target tools\n\n"
        "Generic diagnostics are copied from the donor. Firmware preparation "
        "and contract verification live in the repository-level `tools/bope/` toolkit.\n"
    )


def _copy_helper(donor: Path, destination: Path) -> None:
    source = donor / "helper"
    if not source.is_dir():
        raise BopeError(f"donor helper source is missing: {source}")
    shutil.copytree(source, destination, ignore=shutil.ignore_patterns("build", "__pycache__"))


def create_target_skeleton(donor: Path, destination: Path, info: OtaInfo) -> None:
    if destination.exists():
        raise BopeError(f"target already exists; refusing to overwrite: {destination}")
    destination.mkdir(parents=True)
    _copy_engine(donor, destination / "brazilian-open-payload-engine", info.slug, info.post_build)
    _copy_helper(donor, destination / "helper")
    (destination / "firmware").mkdir()
    (destination / "kernelsu-next").mkdir()
    (destination / ".gitignore").write_text(
        f"firmware/boot_{info.slug.upper()}.img\n"
        "firmware/unpacked/\n"
        f"firmware/vmlinux_{info.slug.upper()}.elf\n"
        "brazilian-open-payload-engine/build/\n"
        "helper/build/\n"
    )
    (destination / "README.md").write_text(
        f"# {info.model} {info.post_build} generated target\n\n"
        f"Generated from the `{info.pre_build}` → `{info.post_build}` Samsung OTA.\n\n"
        "Status: **WIP — device validation required before release.**\n"
    )


def write_firmware_readme(target: Path, info: OtaInfo, artifacts: KernelArtifacts) -> None:
    (target / "firmware/README.md").write_text(
        f"# {info.post_build} firmware evidence\n\n"
        f"Source build: `{info.pre_build}`. Target build: `{info.post_build}`.\n\n"
        f"The OTA `{info.patch_entry}` reconstructs a {info.target_size}-byte boot image "
        f"with SHA-1 `{info.target_sha1}`. The kernel release is "
        f"`{artifacts.identity.release}`.\n\n"
        f"Tracked evidence: `boot.img.p`, `kallsyms_{info.slug.upper()}.kallsyms`, "
        f"and `vmlinux_{info.slug.upper()}.btf`. Regenerable boot, unpacked kernel, "
        "and symbolized ELF are ignored.\n"
    )


def build_target(target: Path, *, ndk: Path | None, logs: Path) -> dict[str, Path]:
    environment = os.environ.copy()
    if ndk:
        environment["ANDROID_NDK_HOME"] = str(ndk)
    engine = target / "brazilian-open-payload-engine"
    helper = target / "helper"
    note("building BOPE, focused host regressions, launcher, and mm factory")
    run_logged(
        [
            "make",
            "clean",
            "so",
            "test-aar-read-plan",
            "test-fops-layout",
            "test-compact-log",
        ],
        logs / "bope-build.log",
        cwd=engine,
        env=environment,
    )
    note("building temporary-root helper")
    run_logged(["make", "clean", "all"], logs / "helper-build.log", cwd=helper, env=environment)
    launcher = sorted((engine / "build").glob("stability-launcher-*"))
    if len(launcher) != 1:
        raise BopeError(
            f"expected one stability launcher, found {len(launcher)} under {engine / 'build'}"
        )
    artifacts = {
        "exploit": engine / "build/payload.so",
        "launcher": launcher[0],
        "mmFactory": engine / "build/mm-exec-factory",
        "helper": helper / "build/cve-2026-43499-root",
    }
    for name, path in artifacts.items():
        if not path.is_file() or path.read_bytes()[:4] != b"\x7fELF":
            raise BopeError(f"built {name} is missing or not ELF: {path}")
    return artifacts


def _build_display(fingerprint: str, incremental: str) -> str:
    try:
        build_id = fingerprint.split(":", 1)[1].split("/")[1]
    except (IndexError, AttributeError):
        return incremental
    return f"{build_id}.{incremental}"


def app_profile(
    info: OtaInfo,
    kernel: KernelArtifacts,
    artifacts: dict[str, Path],
    ksud: Path,
) -> dict[str, object]:
    version_match = re.search(r"v(\d+\.\d+\.\d+)", ksud.name)
    version = version_match.group(1) if version_match else "unknown"
    names = {
        "exploit": f"cve-2026-43499-app-{info.slug}.so",
        "kernelsu": f"ksud-next-v{version}-{info.slug}",
        "helper": f"cve-2026-43499-root-{info.slug}",
        "launcher": f"stability-launcher-{info.slug}",
        "mmFactory": f"mm-exec-factory-{info.slug}",
    }
    sources = {**artifacts, "kernelsu": ksud}
    profile: dict[str, object] = {
        "payloadId": f"{info.device}-{info.post_build}-ksunext",
        "displayName": f"Galaxy S23 Ultra {info.model} | {info.post_build} | KernelSU Next",
        "models": [info.model],
        "kernelVersions": [".".join(kernel.identity.release.split(".")[:3])],
        "buildDisplays": [_build_display(info.post_fingerprint, info.post_build)],
        "fingerprints": [info.post_fingerprint],
        "kernelReleases": [kernel.identity.release],
        "kernelVersionInfos": [kernel.identity.version_info],
    }
    for field, name in names.items():
        source = sources[field]
        profile[field] = {"url": f"asset://{name}", "size": source.stat().st_size}
    return profile


def integrate_app(
    project: Path,
    profile: dict[str, object],
    artifacts: dict[str, Path],
    ksud: Path,
) -> None:
    manifest = project / "app/src/main/assets/targets-v3.json"
    assets = manifest.parent
    document = json.loads(manifest.read_text())
    sources = {**artifacts, "kernelsu": ksud}
    for field, source in sources.items():
        name = str(profile[field]["url"]).removeprefix("asset://")  # type: ignore[index]
        shutil.copy2(source, assets / name)
        (assets / name).chmod(0o755)
    payloads = [item for item in document["payloads"] if item["payloadId"] != profile["payloadId"]]
    payloads.append(profile)
    document["payloads"] = payloads
    atomic_text(manifest, json.dumps(document, indent=2) + "\n")


def file_record(path: Path, relative_to: Path | None = None) -> dict[str, object]:
    rendered = str(path)
    if relative_to:
        try:
            rendered = str(path.relative_to(relative_to))
        except ValueError:
            pass
    return {
        "path": rendered,
        "size": path.stat().st_size,
        "sha256": digest(path),
    }


def write_port_manifest(
    target: Path,
    *,
    final_target: Path,
    project: Path,
    info: OtaInfo,
    donor: Path,
    source_boot: Path,
    kernel: KernelArtifacts,
    contract: ContractResult,
    verification: dict[str, object],
    kernelsu: dict[str, object] | None,
    build_artifacts: dict[str, Path],
    profile: dict[str, object] | None,
) -> Path:
    recorded_verification = dict(verification)
    recorded_verification["header"] = relative_or_absolute(contract.header, target)
    document = {
        "schema": 1,
        "status": "GENERATED_WIP_DEVICE_VALIDATION_REQUIRED",
        "target": {
            "slug": info.slug,
            "directory": str(final_target.relative_to(project)) if final_target.is_relative_to(project) else str(final_target),
            "model": info.model,
            "device": info.device,
            "build": info.post_build,
            "fingerprint": info.post_fingerprint,
            "kernel_release": kernel.identity.release,
            "kernel_version_info": kernel.identity.version_info,
        },
        "source": {
            "donor_target": relative_or_absolute(donor, project),
            "build": info.pre_build,
            "fingerprint": info.pre_fingerprint,
            "boot": file_record(source_boot),
        },
        "ota": {
            "path": str(info.path),
            "sha256": digest(info.path),
            "patch_entry": info.patch_entry,
            "source_boot_sha1": info.source_sha1,
            "target_boot_sha1": info.target_sha1,
            "target_boot_size": info.target_size,
        },
        "kernel": {
            "boot": file_record(kernel.boot, target),
            "kernel": file_record(kernel.kernel, target),
            "kallsyms": file_record(kernel.kallsyms, target),
            "elf": file_record(kernel.elf, target),
            "btf": file_record(kernel.btf, target),
            "base_address": f"0x{kernel.base_address:016x}",
        },
        "contract": {
            "derived_values": contract.derived,
            "changed_values": contract.changed,
            "inherited_calibration_values": contract.inherited,
            "verification": recorded_verification,
        },
        "kernelsu": kernelsu,
        "artifacts": {name: file_record(path, target) for name, path in build_artifacts.items()},
        "app_profile": profile,
    }
    path = target / "port-manifest.json"
    atomic_text(path, json.dumps(document, indent=2, sort_keys=True) + "\n")
    return path
